POST http://localhost:8080/admins/create
authorization: Basic {{adminUserEmail}} {{password}}
Content-Type: application/json

{
  "name": "",
  "surname": "s",
  "password": "Password1234!",
  "email": "admhaaahhasyuinds2sadmin.com"
}

###
GET http://localhost:8080/admins
authorization: Basic {{adminUserEmail}} {{password}}
Content-Type: application/json

###
GET http://localhost:8080/admins/test
authorization: Basic {{adminUserEmail}} {{password}}
Content-Type: application/json